export const routes = {
    main: "/",
    login: "/login",
    register: "/register",
    assistant: "/assistant",
    tickets: "/tickets",
    notifications: "/notifications",
    profile: "/profile",
    settings: "/settings",
    analytics: "/analytics",
    createTicket: "/create-ticket",
    feedback: "/feedback",
    ticketStatus: "/ticket-status",
    myReviews: "/my-reviews",
} as const
